### ISSUE TITLE
Experiment for visualizing on sphere like in header image?

### ISSUE THREAD

**Issue by patcon** [santiag0m/traveling-words#2]
Hi! I'm new to this, but very curious to explore that visualization. Is there a way to derive that from any of the experiments here?

---
<img src="https://github.com/santiag0m/traveling-words/assets/32421689/17e923c9-ff97-4d40-a6eb-fc7a7112b338" width="50%" />

---
Regardless, thanks for this code repo!

**Comment by santiag0m** [comment]
Hi @patcon, the visualization in the paper is a 3D simplification of the high-dimensional dynamics inside the transformer.

To visualize it in 3D, you'd need to perform dimensionality reduction, although the global geometry is lost in this process (so you won't be able to visualize the sphere).

I provide a script to do so [here](https://github.com/santiag0m/traveling-words/blob/137aa6090aef2d3d954998bb3557f9e4a0b1ab41/trajectory.py#L199)
